# Hexo Configuration

# Site
title: Hexo Blog
subtitle: Demo Blog in Hexo Theme Naive
description: Demo Blog in Hexo Theme Naive for Unit Test
keywords: Hexo, Blog, Demo, Naive UI, Hexo Theme Naive
author: Naive
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://chenrt-ggx.github.io/HexoDemoNaive
root: /HexoDemoNaive/
permalink: blog/drop/:hash/
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: true
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true

# Code
highlight:
  enable: false
prismjs:
  enable: false

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'date'

# Pagination
per_page: 10
pagination_dir: page

#  Theme
theme: naive
generate_html: true
favicon: favicon.svg
avatar: /HexoDemoNaive/assets/avatar.svg
bgm: /HexoDemoNaive/assets/standard-jazz-bars.mp3
github: https://github.com/Chenrt-ggx/HexoDemoNaive

# About
email: hexo-theme-naive@demo.com
introductions:
  - 这是一个 Hexo Theme Naive 主题的单元测试页。
  - 如果你能看到这里，这个主题目前大概是正常的。
repos:
  - name: hexojs/hexo
    url: https://github.com/hexojs/hexo
    description: A fast, simple & powerful blog framework, powered by Node.js.
  - name: hexojs/hexo-cli
    url: https://github.com/hexojs/hexo-cli
    description: Command line interface for Hexo
  - name: vuejs/core
    url: https://github.com/vuejs/core
    description: Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.
  - name: vuejs/router
    url: https://github.com/vuejs/router
    description: The official router for Vue.js
  - name: vuejs/pinia
    url: https://github.com/vuejs/pinia
    description: Intuitive, type safe, light and flexible Store for Vue using the composition api with DevTools support.
  - name: tusen-ai/naive-ui
    url: https://github.com/tusen-ai/naive-ui
    description: A Vue 3 Component Library. Fairly Complete. Theme Customizable. Uses TypeScript. Fast.
friends:
  - name: HexoJS
    page: https://github.com/hexojs
    avatar: https://avatars.githubusercontent.com/u/6375567
  - name: VueJS
    page: https://github.com/vuejs
    avatar: https://avatars.githubusercontent.com/u/6128107
  - name: TusenAI
    page: https://github.com/tusen-ai
    avatar: https://avatars.githubusercontent.com/u/109735111
